### ISSUE TITLE
pod deploy from README fails

### ISSUE THREAD

**Issue by rvs** [lf-edge/eden#267] opened 2020-09-15 18:53 UTC
Here's what I'm observing on the latest build of Eden (all done from 100% clean slate -- no prior state):

```
eden pod deploy -p 8028:80 docker://nginx
FATA[0000] Port 8028 already in use
```

This used to work before

**Comment by giggsoff** [comment] 2020-09-15 19:02
Could you please run `eden pod ps`?

**Comment by rvs** [comment] 2020-09-15 22:40
It is empty -- all of this done on a freshly booted Mac OX -- with a clean Eden repo and 0 prior configuration in .eden.

**Comment by mydatascience** [comment] 2020-09-16 03:45
can't reproduce. Are you using the local eve? 
`INFO[0000] Start EVE: qemu-system-x86_64 -display none -serial telnet:localhost:7777,server,nowait -nodefaults -no-user-config -smbios type=1,serial=31415926 -machine q35,accel=hvf -cpu kvm64,kvmclock=off -drive file=/Users/fleandr/eden/dist/default-images/eve/live.img,format=qcow2 -readconfig /Users/fleandr/.eden/default-qemu.conf  
INFO[0000] With pid: /Users/fleandr/eden/dist/eve.pid ; log: /Users/fleandr/eden/dist/eve.log 
INFO[0006] EVE is starting                              
(base) Vladimirs-MacBook-Air:eden fleandr$ ./eden status
EVE state: not onboarded

✔ Adam status: container with name eden_adam is running
	Adam is expected at https://192.168.1.110:3333
	For local Adam you can run 'docker logs eden_adam' to see logs
✔ Registry status: container with name eden_registry is running
	Registry is expected at https://192.168.1.110:5000
	For local registry you can run 'docker logs eden_registry' to see logs
✔ Redis status: container with name eden_redis is running
	Redis is expected at redis://192.168.1.110:6379
	For local Redis you can run 'docker logs eden_redis' to see logs
✔ EServer process status: container with name eden_eserver is running
	EServer is expected at http://192.168.1.110:8888 from EVE
	For local EServer you can run 'docker logs eden_eserver' to see logs
? EVE status: undefined (no onboarded EVE)
✔ EVE on Qemu status: running with pid 2244
	Logs for local EVE at: /Users/fleandr/eden/dist/eve.log
```
(base) Vladimirs-MacBook-Air:eden fleandr$ df -h
Filesystem      Size   Used  Avail Capacity iused               ifree %iused  Mounted on
/dev/disk1s1   113Gi  106Gi  3.6Gi    97% 1435729 9223372036853340078    0%   /
devfs          185Ki  185Ki    0Bi   100%     640                   0  100%   /dev
/dev/disk1s4   113Gi  3.0Gi  3.6Gi    46%       3 9223372036854775804    0%   /private/var/vm
map -hosts       0Bi    0Bi    0Bi   100%       0                   0  100%   /net
map auto_home    0Bi    0Bi    0Bi   100%       0                   0  100%   /home
(base) Vladimirs-MacBook-Air:eden fleandr$ ./eden eve onboard
INFO[0000] Adam waiting for EVE registration (0) of (20) 
INFO[0020] Adam waiting for EVE registration (1) of (20) 
INFO[0040] Adam waiting for EVE registration (2) of (20) 
INFO[0060] Adam waiting for EVE registration (3) of (20) 
INFO[0080] Device uuid: d966957a-20b3-44d4-9b9c-990f4b908f97 
INFO[0080] config updated /Users/fleandr/.eden/devUUID-d966957a-20b3-44d4-9b9c-990f4b908f97.json 
INFO[0080] state updated /Users/fleandr/.eden/state-9c38e956-e3d2-44af-9e33-8d6f5b5d23b2.yml 
INFO[0080] config updated /Users/fleandr/.eden/devUUID-d966957a-20b3-44d4-9b9c-990f4b908f97.json 
INFO[0080] state updated /Users/fleandr/.eden/state-9c38e956-e3d2-44af-9e33-8d6f5b5d23b2.yml 
INFO[0080] onboarded                                    
INFO[0080] device UUID: d966957a-20b3-44d4-9b9c-990f4b908f97 
(base) Vladimirs-MacBook-Air:eden fleandr$ eden pod deploy -p 8028:80 docker://nginx
-bash: eden: command not found
(base) Vladimirs-MacBook-Air:eden fleandr$ ./eden pod deploy -p 8028:80 docker://nginx
INFO[0000] new datastore created b7789b6e-9b5d-4581-b4e8-1ce465ffdd61 
INFO[0000] new image created 7b41bea2-ea9a-497d-b0c6-82381c542955 
INFO[0000] Try to obtain info about volumes, please wait 
INFO[0002] new app created 6c898949-c412-41c9-95cc-0de4941eec28 
INFO[0002] config updated /Users/fleandr/.eden/devUUID-d966957a-20b3-44d4-9b9c-990f4b908f97.json 
INFO[0002] state updated /Users/fleandr/.eden/state-9c38e956-e3d2-44af-9e33-8d6f5b5d23b2.yml 
INFO[0002] deploy pod wizardly_williamson with docker://nginx request sent 
(base) Vladimirs-MacBook-Air:eden fleandr$ ./eden pod ps
NAME			IMAGE			UUID				INTERNAL	EXTERNAL	STATE(ADAM)	LAST_STATE(EVE)
wizardly_williamson	library/nginx:latest	6c898949-c412-41c9-95cc-0de4941eec28	-:80		127.0.0.1:8028	IN_CONFIG	UNKNOWN
(base) Vladimirs-MacBook-Air:eden fleandr$ ./eden pod ps
NAME			IMAGE			UUID				INTERNAL	EXTERNAL	STATE(ADAM)	LAST_STATE(EVE)
wizardly_williamson	library/nginx:latest	6c898949-c412-41c9-95cc-0de4941eec28	-:80		127.0.0.1:8028	IN_CONFIG	UNKNOWN
(base) Vladimirs-MacBook-Air:eden fleandr$ ./eden pod ps
NAME			IMAGE			UUID				INTERNAL	EXTERNAL	STATE(ADAM)	LAST_STATE(EVE)
wizardly_williamson	library/nginx:latest	6c898949-c412-41c9-95cc-0de4941eec28	10.1.0.2:80	127.0.0.1:8028	IN_CONFIG	INSTALLED
(base) Vladimirs-MacBook-Air:eden fleandr$ ./eden pod ps
NAME			IMAGE			UUID				INTERNAL	EXTERNAL	STATE(ADAM)	LAST_STATE(EVE)
wizardly_williamson	library/nginx:latest	6c898949-c412-41c9-95cc-0de4941eec28	10.1.0.2:80	127.0.0.1:8028	IN_CONFIG	RUNNING
(base) Vladimirs-MacBook-Air:eden fleandr$ 

```

**Comment by giggsoff** [comment] 2020-09-16 18:53
Another part of readme: #270 
Seems, that we need to re-check https://github.com/lf-edge/eden/blob/master/pkg/controller/device.go#L86 with multiple EVE variant.

**Comment by rvs** [comment] 2020-09-16 19:48
Yup. Feel free to close this one and open a new one to track issues with multiple EVEs.

**Comment by mydatascience** [comment] 2020-09-24 19:57
closing. will open a new if we have an issue

**Closed by mydatascience** 2020-09-24 19:57 UTC
