### ISSUE TITLE
Enchase linuxkits implementation of where metadata can be located

### ISSUE THREAD

**Issue by rvs** [lf-edge/eden#15] opened 2020-04-10 18:17 UTC
We need to properly deal with how EVE passes metadata to the VM, upstream it into linuxkit and remove the local workarounds.

Arguably, EVE is doing the right thing here following cloud-config/cloudinit standard so perhaps on the linuxkit side we can frame it more along the lines of following cloudinit

**Comment by deitch** [comment] 2020-04-11 18:28
Have you looked at [pkg/metadata](https://github.com/linuxkit/linuxkit/tree/master/pkg/metadata) ?

**Comment by rvs** [comment] 2020-04-11 18:33
Yes @deitch but according to @giggsoff that doesn't seem to look for metadata in places where cloudinit would look for (and that's where EVE mounts that metadata). Hence this issue. @giggsoff can provide more details on how linuxkit needs to be updated.

**Comment by deitch** [comment] 2020-04-11 18:34
The nice thing about linuxkit is that it’s all independent containers. We can stick something else in there, or if we need to update pkg/metadata, we can. What’s missing?

**Comment by giggsoff** [comment] 2020-04-11 21:09
Hi, @deitch . In [cloud-init](https://cloudinit.readthedocs.io/en/latest/topics/datasources/nocloud.html) and [EVE](https://github.com/lf-edge/eve/blob/d85a92d3d2d9958be7e7d31a9ac0dd8f90c57f1d/pkg/pillar/cmd/domainmgr/domainmgr.go#L1884) metadata is located in the root of CD-ROM in files "user-data" and "meta-data". But in [linuxkit](https://github.com/linuxkit/linuxkit/blob/3716b312f6bf07cc0496b0ec051ae71336f47a59/pkg/metadata/provider_cdrom.go#L45) metadata is obtained from file with name "config" in the CD-ROM root.

@rvs also, I noticed, that for KVM type of virtualization in EVE (for "VM", not container), drive with metadata is vdb, not sr0.

**Comment by deitch** [comment] 2020-04-12 07:21
So the issue is that linuxkit assumes that a cdrom will have data in the cdrom's root as `/config`, but cloud-init (per the link to the spec you have above) says it should in the cdrom's root as `/user-data` and `/meta-data`.

Please open an issue on linuxkit just stating that the cdrom read is incorrect for cloud-init. We should read both.

**Comment by rvs** [comment] 2020-04-16 20:21
Hey @giggsoff @sadov did you guys open up linuxkit issue yet? Please do so and link it here.

**Comment by giggsoff** [comment] 2020-04-17 12:22
Hi, @rvs @sadov I opened the Issue in linuxkit project:
linuxkit/linuxkit#3501

**Comment by deitch** [comment] 2020-04-20 11:55
@giggsoff it just merged in, you can use `linuxkit/metadata:04ce7519c2ea2eaf99bbdc76bb01fc036eed7ab0` or wait for it to go into a formal release.

Are there other issues that need to be resolved with it? Please take a look and open new issues so we can close this out.

**Comment by giggsoff** [comment] 2020-04-20 14:00
@deitch thanks, it works, I can see userdata in /run/config/userdata, but only for XEN HV.
As I previously mentioned, KVM variant of HV in EVE uses /dev/vdb, not /dev/sr0 for metadata.
And I found the mention in [nocloud.rst](https://github.com/canonical/cloud-init/blob/master/doc/rtd/topics/datasources/nocloud.rst):
> You can provide meta-data and user-data to a local vm boot via files on a vfat or iso9660 filesystem. The filesystem volume label must be cidata or CIDATA.
So, not only /dev/sr[0-9]*, but also filesystems with labels cidata or CIDATA should be in scope of search.

**Comment by deitch** [comment] 2020-04-20 14:07
Good point. Please open a separate issue on linuxkit on the device.

I find it strange that it is `/dev/vdb` and not a linux standard `/dev/sr[0-9]*`. Is that configurable? Would it be easier to just have it be at a "normal" path?

**Comment by rvs** [comment] 2020-04-21 03:40
Hey @deitch -- you can expect a single device name -- those will forever change. As @giggsoff suggests can we simply search all devices with a particular label (lsblk -o NAME,LABEL equivalent)?

**Comment by deitch** [comment] 2020-04-21 04:00
So your argument is that we should not rely on a cdrom being `/dev/sr[0-9]*` but instead (or in addition) look for any device whose name is `cidata` or `CIDATA`?

Open an issue to that extent on linuxkit

**Comment by giggsoff** [comment] 2020-04-21 10:25
Hi, @deitch new Issue in linuxkit project:
linuxkit/linuxkit#3506

**Comment by deitch** [comment] 2020-05-01 15:08
This has been resolved. Use `linuxkit/metadata: dc5bcfa45946053145391ceabe33729c8b9507a1` or any later commit, eventually release.

**Closed by deitch** 2020-05-01 15:08 UTC
